### ISSUE TITLE
主要功能都无法使用

### ISSUE THREAD

**Issue by w311ang** [NitroRCr/WordsAway_Android#1]
零宽间隔（普通）
每两字双重反转（增强）
每行双重反转（增强）
转为竖向排列（物理）
替换英文和数字
使用均会导致输出为空，这是一个未开发完的版本吗？

**Comment by NitroRCr** [comment]
感谢反馈，没想到这个也有人看哈哈  
确实如此，这是好久之前的版本  
之前因为中考的原因，鸽了太久，这两天才开始继续开发，但没有发布  
现在v0.0.4版本已经发布，解决了部分问题，并增加了功能，但依然是测试版  
输出为空的问题只出现在Android 7.0 以下，现已解决  
（第一次Android开发，确实问题挺多）

**Comment by w311ang** [comment]
> 感谢反馈，没想到这个也有人看哈哈
> 确实如此，这是好久之前的版本
> 之前因为中考的原因，鸽了太久，这两天才开始继续开发，但没有发布
> 现在v0.0.4版本已经发布，解决了部分问题，并增加了功能，但依然是测试版
> 输出为空的问题只出现在Android 7.0 以下，现已解决
> （第一次Android开发，确实问题挺多）

哈哈，辛苦了
